galaxy_info:
  role_name: gitea
  author: nodiscc
  description: Gitea self-hosted Git service/software forge
  license: GPL-3.0
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - git
    - project
    - development
    - issues
    - wiki
    - vcs
    - web
dependencies:
  # - nodiscc.xsrv.common
  # - nodiscc.xsrv.monitoring
  # - nodiscc.xsrv.backup
  - nodiscc.xsrv.apache
  - { role: nodiscc.xsrv.mariadb, when: gitea_db_type == "mysql" }
  - { role: nodiscc.xsrv.postgresql, when: gitea_db_type == "postgres" }
