---

galaxy_info:
  role_name: gitea
  author: nodiscc
  description: Gitea self-hosted Git service/software forge
  license: GPL-3.0
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - git
    - project
    - development
    - issues
    - wiki
    - vcs
    - web
dependencies:
  # - common
  # - backup
  - apache or xsrv.xsrv.apache
  - { role: mariadb or xsrv.xsrv.mariadb, when: gitea_db_type == "mysql" }
  - { role: postgresql or xsrv.xsrv.postgresql, when: gitea_db_type == "postgres" }

