###### BACKUPS ############

- name: copy rsnapshot configuration for samba backups
  template:
    src: etc_rsnapshot.d_samba.conf.j2
    dest: /etc/rsnapshot.d/samba.conf
    mode: 0600
  when: '"nodiscc.xsrv.backup" in role_names'
  notify: check rsnapshot configuration
