---

##### PACKAGES #####

- name: install required packages
  apt:
    state: present
    package:
      - php-gmp
      - php-curl
      - php-gd
      - php-imagick
      - php-intl
      - php-json
      - php-ldap
      - php-sqlite3
      - php-mbstring
      - php-xml
      - php-zip
      - php-bz2
      - php-smbclient
      - php-imap
      - php-apcu
      - ffmpeg
      - acl

###### FAIL2BAN ##########

- name: copy nextcloud fail2ban jail config
  template:
    src: etc_fail2ban_jail.d_nextcloud.conf.j2
    dest: /etc/fail2ban/jail.d/nextcloud.conf
    mode: 0600
  tags: fail2ban
  notify: reload fail2ban

- name: copy fail2ban nextcloud-auth filter
  template:
    src: etc_fail2ban_filter.d_nextcloud-auth.conf.j2
    dest: /etc/fail2ban/filter.d/nextcloud-auth.conf
    mode: 0600
  tags: fail2ban
  notify: reload fail2ban

##### BACKUPS #####

- name: copy rsnapshot configuration for nextcloud backups
  template:
    src: etc_rsnapshot.d_nextcloud.conf.j2
    dest: /etc/rsnapshot.d/nextcloud.conf
    mode: 0600
  when: '"nodiscc.xsrv.backup" in role_names'
  notify: check rsnapshot configuration


### GET/SET FACTS ###

- name: check if nextcloud installation directory exists
  stat:
    path: "{{ nextcloud_install_dir }}"
  register: nextcloud_dir

- name: abort on unsupported conditions
  fail:
    msg: "ERROR: unsupported conditions: nextcloud_dir.stat.exists: {{ nextcloud_dir.stat.exists }}, but ansible_local.nextcloud.installed.version says otherwise" # noqa 204
  when: '((ansible_local.nextcloud.installed.version is defined) and (not nextcloud_dir.stat.exists)) or
         ((ansible_local.nextcloud.installed.version is undefined) and (nextcloud_dir.stat.exists))'

- name: set the default installation action (do nothing)
  set_fact:
    nextcloud_action: none

- name: check if initial installation should be performed
  set_fact:
    nextcloud_action: initial
  when:
    - ansible_local.nextcloud.installed.version is undefined
    - not nextcloud_dir.stat.exists

- name: check if upgrade should be performed
  set_fact:
    nextcloud_action: upgrade
  when:
    - ansible_local.nextcloud.installed.version is defined
    - ansible_local.nextcloud.installed.version < nextcloud_version
    - nextcloud_dir.stat.exists

#- debug:
#    msg: "action: {{ nextcloud_action }}, nextcloud_dir.stat.exists: {{ nextcloud_dir.stat.exists }}, nextcloud_version: {{ nextcloud_version }}"


### DOWNLOAD/INSTALLATION ###

- name: download nextcloud zip
  get_url:
    url: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.zip"
    dest: "/root/nextcloud-{{ nextcloud_version }}.zip"
  when: nextcloud_action == 'initial' or nextcloud_action == 'upgrade'

- name: create nextcloud zip extraction directory
  file:
    path: /root/nextcloud-unpack
    state: directory
    mode: 0750
  when: nextcloud_action == 'initial' or nextcloud_action == 'upgrade'

- name: extract nextcloud zip
  unarchive:
    src: "/root/nextcloud-{{ nextcloud_version }}.zip"
    dest: "/root/nextcloud-unpack"
    remote_src: yes
    mode: u=rwX
  no_log: True
  when: nextcloud_action == 'initial' or nextcloud_action == 'upgrade'

- name: give write permissions to the webserver
  file:
    path: "{{ item.path }}"
    group: www-data
    mode: "{{ item.mode }}"
    recurse: no
  with_items:
    - { path: "/root/nextcloud-unpack/nextcloud/apps", mode: "g+w" }
    - { path: "/root/nextcloud-unpack/nextcloud/config", mode: "g+w" }
    - { path: "/root/nextcloud-unpack/nextcloud/themes", mode: "g+w" }
    - { path: "/root/nextcloud-unpack/nextcloud/occ", mode: "g+X" }
  when: nextcloud_action == 'initial' or nextcloud_action == 'upgrade'

- name: move old nextcloud installation to temporary dir
  command: mv '{{ nextcloud_install_dir }}' '{{ nextcloud_install_dir }}.old'
  args:
    removes: '{{ nextcloud_install_dir }}'
  when: nextcloud_action == 'upgrade'

- name: move nextcloud extraction directory to install directory
  command: mv /root/nextcloud-unpack/nextcloud '{{ nextcloud_install_dir }}'
  when: nextcloud_action == 'initial' or nextcloud_action == 'upgrade'


### CONFIGURATION ###

- name: create nextcloud data directory
  file:
    path: "/var/nextcloud/data"
    state: directory
    owner: root
    group: www-data
    mode: 0770

- name: run first setup (this can take a while)
  become: yes
  become_user: www-data
  command: /usr/bin/php occ \
           maintenance:install \
           --database="{{ nextcloud_db_type }}" \
           --database-host="{{ nextcloud_db_host }}" \
           --database-name="{{ nextcloud_db_name }}" \
           --database-user="{{ nextcloud_db_user }}" \
           --database-pass="{{ nextcloud_db_password }}" \
           --admin-user="{{ nextcloud_user }}" \
           --admin-pass="{{ nextcloud_password }}"
           --data-dir="{{ nextcloud_data_dir }}"
           --admin-email="{{ nextcloud_admin_email }}"
  register: nextcloud_first_setup
  args:
    chdir: "{{ nextcloud_install_dir }}"
  failed_when: nextcloud_first_setup.rc !=0 and 'Command "maintenance:install" is not defined.' not in nextcloud_first_setup.stderr  # noqa 204
  changed_when: nextcloud_first_setup.rc == 0
  when:
    - nextcloud_action == 'initial'

- name: copy config.php from old installation
  copy:
    remote_src: yes
    src: '{{ nextcloud_install_dir }}.old/config/config.php'
    dest: '{{ nextcloud_install_dir }}/config/config.php'
    owner: www-data
    group: www-data
    mode: 0660
  when:
    - nextcloud_action == 'upgrade'

# TODO: not idempotent, replace with template-based management of config.php
# TODO: if this fails the install will be left in a broken state, the working copy is still at {{ nextcloud_fqdn }}.old
- name: set nextcloud config.php values (not idempotent, returns changed every time - occ doesn't report changed status)
  become: yes
  become_user: www-data
  command: /usr/bin/php ./occ config:system:set --type={{ item.type | default('string') }} {{ item.key }} --value={{ item.value }} # noqa 301
  args:
    chdir: "{{ nextcloud_install_dir }}/"
  with_items:
    - { key: "trusted_domains 1", value: "{{ nextcloud_fqdn }}" }
    - { key: "overwrite.cli.url", value: "{{ nextcloud_full_url }}" }
    - { key: "datadir", value: "{{ nextcloud_data_dir }}" }
    - { key: "dbtype", value: "{{ nextcloud_db_type }}" }
    - { key: "dbname", value: "{{ nextcloud_db_name }}" }
    - { key: "dbhost", value: "{{ nextcloud_db_host }}" }
    - { key: "dbuser", value: "{{ nextcloud_db_user }}" }
    - { key: "dbpassword", value: "{{ nextcloud_db_password }}", no_log: True }
    - { key: "logtimezone", value: "UTC" }
    - { key: "log_type", value: "file" }
    - { key: "log_authfailip", value: "true", type: "boolean" }
    - { key: "loglevel", value: "1", type: "integer" }
    - { key: "trashbin_retention_obligation", value: "auto" }
    - { key: "memcache.local", value: '\\OC\\Memcache\\APCu' }
    - { key: "share_folder", value: '{{ nextcloud_share_folder }}' }
  no_log: "{{ item.no_log | default(False) }}"
  tags: nextcloud_config_php


# trashbin_retention_obligation:
#   auto: keep for 30 days, then delete IF space needed
#   D, auto: keep at least D+ days, then delete IF space needed
#   auto, D: max D days, but delete if space needed
#   D1, D2: keep lat east D1 days and max D2 days
#   disabled: auto clean disabled

- name: run nextcloud upgrade command
  become: True
  become_user: www-data
  command: /usr/bin/php ./occ upgrade
  args:
    chdir: "{{ nextcloud_install_dir }}"
  register: nextcloud_upgrade
  changed_when: not 'Nextcloud is already at the latest version' in nextcloud_upgrade.stdout
  when:
    - (nextcloud_action == 'initial') or (nextcloud_action == 'upgrade')

- name: schedule nextcloud background tasks
  cron:
    user: www-data
    cron_file: nextcloud
    minute: "*/5"
    job: "/usr/bin/php -f {{ nextcloud_install_dir }}/cron.php"
    name: "run nextcloud background tasks"

##### ANSIBLE FACTS #####

- name: create ansible facts.d directory
  file:
    path: /etc/ansible/facts.d
    state: directory
    mode: 0755

- name: create nextcloud installed fact file
  template:
    src: etc_ansible_facts.d_nextcloud.fact.j2
    dest: /etc/ansible/facts.d/nextcloud.fact
    mode: 0644

###### NEXTCLOUD APPLICATIONS ######

- include: nextcloud-applications.yml

### CLEANUP ###

- name: remove nextcloud zip extraction directory
  file:
    path: /root/nextcloud-unpack
    state: absent

- name: remove old nextcloud installation
  file:
    path: '{{ nextcloud_install_dir }}.old'
    state: absent
  no_log: True
  when:
    - nextcloud_action == 'upgrade'
