galaxy_info:
  role_name: backup
  author: "nodiscc"
  description: "Rsnapshot remote/local backup service"
  license: GPL-3.0
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 9
        - 10
    - name: Ubuntu
      versions:
        - 18
        - 19
  galaxy_tags:
    - backup
    - incremental
    - rsnapshot
dependencies: []
#   - nodiscc.xsrv.common
