##### CHECKS FOR MONITORING ROLE #####

- name: check that mandatory variables are correctly defined
  assert:
    that:
      - needrestart_autorestart_services == needrestart_autorestart_services|bool
      - netdata_allow_connections_from is string
      - netdata_cloud_enabled == netdata_cloud_enabled|bool
      - netdata_dbengine_disk_space == netdata_dbengine_disk_space|int
      - netdata_dbengine_page_cache_size == netdata_dbengine_page_cache_size|int
      - netdata_disable_access_log == netdata_disable_access_log|bool
      - netdata_disable_debug_log == netdata_disable_debug_log|bool
      - netdata_disable_error_log == netdata_disable_error_log|bool
      - netdata_http_checks|type_debug == "list"
      - netdata_install_method in ['packagecloud', 'binary']
      - netdata_logcount_error_threshold_crit == netdata_logcount_error_threshold_crit|int
      - netdata_logcount_error_threshold_warn == netdata_logcount_error_threshold_warn|int
      - netdata_logcount_git_url is string
      - netdata_logcount_notification_to is string
      - netdata_logcount_update_interval == netdata_logcount_update_interval|int
      - netdata_logcount_warning_threshold_warn == netdata_logcount_warning_threshold_warn|int
      - netdata_min_running_docker_containers == netdata_min_running_docker_containers|int
      - netdata_modtime_checks|type_debug == "list"
      - netdata_needrestart_git_url is string
      - netdata_port_checks|type_debug == "list"
      - netdata_process_checks|type_debug == "list"
      - netdata_self_monitoring_enabled == netdata_self_monitoring_enabled|bool
      - netdata_update_every == netdata_update_every|int
      - netdata_version is string
      - rsyslog_monitor_apache_accesslog == rsyslog_monitor_apache_accesslog|bool
      - rsyslog_monitor_netdata == rsyslog_monitor_netdata|bool
      - setup_rsyslog == setup_rsyslog|bool
      - setup_monitoring_cli_utils == setup_monitoring_cli_utils|bool
