##### PACKAGES #####

- name: install transmission
  apt:
    package: transmission-daemon
    state: present

##### CONFIGURATION #####

- name: copy transmission-daemon configuration
  template:
    src: "etc_transmission-daemon_settings.json.j2"
    dest: "/etc/transmission-daemon/settings.json"
    owner: debian-transmission
    group: debian-transmission
    mode: 0600
  notify: reload transmission-daemon
  no_log: True

- name: add ansible user to debian-transmission group
  user:
    name: "{{ ansible_user }}"
    groups: debian-transmission
    append: yes

- name: create symlink to download directory in main users home
  file:
    state: link
    src: "{{ transmission_download_dir }}"
    dest: "/home/{{ ansible_user }}/TORRENTS"

##### FAIL2BAN #####
# transmission login failures are logged by apache
# bans are enforced by the apache-auth jail (see apache role)

##### BACKUPS #####

- name: copy rsnapshot configuration for transmission backups
  template:
    src: etc_rsnapshot.d_transmission.conf.j2
    dest: /etc/rsnapshot.d/transmission.conf
    mode: 0600
  notify: check rsnapshot configuration
  when: '"nodiscc.xsrv.backup" in role_names'


##### SERVICES #####

- name: ensure transmission configuration is applied (flush handlers)
  meta: flush_handlers

- name: enable transmission-daemon service
  service:
    name: transmission-daemon
    state: started
    enabled: yes
  when: transmission_enable_service

- name: disable transmission-daemon service
  service:
    name: transmission-daemon
    state: stopped
    enabled: no
  when: not transmission_enable_service
