- name: check that mandatory variables are correctly defined
  assert:
    that:
      - gitea_admin_email is not search("CHANGEME")
      - gitea_admin_password is not search("CHANGEME")
      - gitea_admin_username is not search("CHANGEME")
      - gitea_https_mode in ['selfsigned', 'letsencrypt']
      - gitea_base_url is not search("CHANGEME")
      - gitea_db_host is not search("CHANGEME")
      - gitea_db_password is not search("CHANGEME")
      - gitea_db_port == gitea_db_port|int
      - gitea_db_type in ['postgres', 'mysql']
      - gitea_db_user is not search("CHANGEME")
      - gitea_default_private in ['last', 'private', 'public']
      - gitea_disable_gravatar in ['true', 'false']
      - gitea_disable_registration in ['true', 'false']
      - gitea_enable_api in ['true', 'false']
      - gitea_api_max_results == gitea_api_max_results|int
      - gitea_enable_service == gitea_enable_service|bool
      - gitea_force_private in ['true', 'false']
      - gitea_fqdn is not search("CHANGEME")
      - gitea_mailer_enabled == gitea_mailer_enabled|bool
      - gitea_min_password_length == gitea_min_password_length|int
      - gitea_offline_mode in ['true', 'false']
      - gitea_require_signin in ['true', 'false']
      - gitea_secret_key is not search("CHANGEME")
      - gitea_oauth2_jwt_secret is not search("CHANGEME")
      - gitea_lfs_jwt_secret is not search("CHANGEME")
      - gitea_internal_token is not search("CHANGEME")
      - gitea_show_user_email in ['true', 'false']
      - gitea_user_home is string
      - gitea_user_repo_limit == gitea_user_repo_limit|int
      - gitea_version is string

- name: check that postgresql or mariadb roles are enabled
  debug:
    msg: "WARNING: postgresql or mariadb roles are not enabled on this host. Deployment will fail unless gitea has been configured to use a remote database host."
  when:
      - 'postgresql' not in role_names
      - 'mariadb' not in role_names