---

- name: limits.conf
  become: 'yes'
  template:
    src: etc/security/limits.conf.j2
    dest: /etc/security/limits.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - limits.conf
