galaxy_info:
  role_name: apache
  author: "nodiscc <nodiscc@gmail.com>"
  description: "apache web server + mod_php interpreter"
  license: "GPL-3.0"
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - web
    - apache
    - php
    - server
    - lamp
dependencies:
  - nodiscc.xsrv.common
