galaxy_info:
  role_name: docker
  author: geerlingguy
  description: "Docker container management engine"
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - web
    - system
    - containers
    - docker
    - orchestration
    - compose
    - server
dependencies:
  - nodiscc.xsrv.common
  # - nodiscc.xsrv.monitoring
